### TC-CATEGORY-007: Thêm danh mục thất bại khi không có token (Unauthorized)

@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/categories
Content-Type: application/json

{
  "name": "Điện tử"
}
