# TC-AUTH-STT-03: Đăng nhập thành công sau 1 lần đăng nhập sai
@baseUrl = http://localhost:3000/api

### 1. Đăng nhập sai lần 1
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "test@eshop.com",
    "password": "WrongPassword123!"
}

### 2. Đăng nhập đúng (sau 1 lần sai -> Thành công & Reset counter)
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "test@eshop.com",
    "password": "Test1234!"
}
